name: Terraform Module CI


on:
push:
branches: [ main ]
pull_request:
branches: [ main ]


jobs:
validate:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Setup Terraform
uses: hashicorp/setup-terraform@v3
with:
terraform_version: 1.6.6


- name: Terraform Format
run: terraform fmt -check -recursive


- name: Terraform Init (no backend)
run: terraform init -backend=false


- name: Terraform Validate
run: terraform validate


# Optional linters (uncomment if added)
# - name: Install tflint
# run: |
# curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
# tflint --init
# tflint --recursive


release:
if: startsWith(github.ref, 'refs/tags/v')
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Build README tables (optional)
run: echo "Tagged release ${GITHUB_REF#refs/tags/}"