name: Terraform Module CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Init (no backend)
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate

    # Optional linters (uncomment if added)
    # - name: Install tflint
    # run: |
    # curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    # tflint --init
    # tflint --recursive

  release:  # This must be at the same level as the 'validate' job
    if: startsWith(github.ref, 'refs/tags/v') # Indent two spaces
    runs-on: ubuntu-latest # Indent two spaces
    steps: # Indent two spaces
    - uses: actions/checkout@v4 # Indent four spaces
    - name: Build README tables (optional) # Indent four spaces
      run: echo "Tagged release ${GITHUB_REF#refs/tags/}" # Indent six spaces